#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    May 17, 2020 07:02:02 PM -03  platform: Windows NT

import sys
import json
with open('Farmacia.json', encoding='utf-8') as archivoFar:
    lstFarmacia = json.load(archivoFar)
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global lbl_Provincia
    lbl_Provincia = tk.StringVar()
    lbl_Provincia.set('Ingrese una Provincia')
    global but_cal
    but_cal = tk.StringVar()
    but_cal.set('Calcular')
    global lbl_far
    lbl_far = tk.StringVar()
    lbl_far.set('Cantidad de Farmacias')
    global ingreprov
    ingreprov = tk.StringVar()
    global cantfarmacia
    cantfarmacia = tk.StringVar()
    global lbl_id
    lbl_id = tk.StringVar()
    lbl_id.set('Establecimiento ID')
    global Entry_id
    Entry_id = tk.StringVar()
    global but_busc
    but_busc = tk.StringVar()
    but_busc.set('Buscar')
    global lbl_nombre
    lbl_nombre = tk.StringVar()
    lbl_nombre.set('Nombre')
    global lbl_loca
    lbl_loca = tk.StringVar()
    lbl_loca.set('Localidad')
    global lbl_prov
    lbl_prov = tk.StringVar()
    lbl_prov.set('Provincia')
    global lbl_depar
    lbl_depar = tk.StringVar()
    lbl_depar.set('Departamento')
    global entry_nombre
    entry_nombre = tk.StringVar()
    global entry_loca
    entry_loca = tk.StringVar()
    global entry_prov
    entry_prov = tk.StringVar()
    global entry_depar
    entry_depar = tk.StringVar()
    global lbl_finan
    lbl_finan = tk.StringVar()
    lbl_finan.set('Financiamiento')
    global lbl_domi
    lbl_domi = tk.StringVar()
    lbl_domi.set('Domicilio')
    global entry_financ
    entry_financ = tk.StringVar()
    global entry_domicilio
    entry_domicilio = tk.StringVar()
    global lbl_cposalh
    lbl_cposalh = tk.StringVar()
    lbl_cposalh.set('Codigo Postal Hasta')
    global lbl_cpostald
    lbl_cpostald = tk.StringVar()
    lbl_cpostald.set('Codigo Postal Desde')
    global cphasta
    cphasta = tk.StringVar()
    global entry_cpdesde
    entry_cpdesde = tk.StringVar()
    global but_cpbus
    but_cpbus = tk.StringVar()
    but_cpbus.set('Buscar')
    global lbl_cant
    lbl_cant = tk.StringVar()
    lbl_cant.set('Cantidad')
    global entry_cantidad
    entry_cantidad = tk.StringVar()
    global lbl_texlargo
    lbl_texlargo = tk.StringVar()
    lbl_texlargo.set('Provincias con mas farmacias cuyo origen de financiamiento sea mutual')
    global but_BusMutual
    but_BusMutual = tk.StringVar()
    but_BusMutual.set('Buscar')
    global lbl_nombremutual
    lbl_nombremutual = tk.StringVar()
    lbl_nombremutual.set('Nombre')
    global lbl_cantidadmutual
    lbl_cantidadmutual = tk.StringVar()
    lbl_cantidadmutual.set('Cantidad')
    global entry_nombmutual
    entry_nombmutual = tk.StringVar()
    global entry_cantmutual
    entry_cantmutual = tk.StringVar()
    global lbl_ingreProv
    lbl_ingreProv = tk.StringVar()
    lbl_ingreProv.set('Ingrese una Provincia')
    global promingprov
    promingprov = tk.StringVar()
    global finanprom
    finanprom = tk.StringVar()
    global lbl_unfinan
    lbl_unfinan = tk.StringVar()
    lbl_unfinan.set('Un Financiamiento')
    global but_promedio
    but_promedio = tk.StringVar()
    but_promedio.set('Promendio por Departamento')
    global lbl_cantProm
    lbl_cantProm = tk.StringVar()
    lbl_cantProm.set('Cantidad')
    global entry_cantProm
    entry_cantProm = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def buscar_mutual():
    provincia1="BUENOS AIRES"
    provincia2="CABA"
    cont1=0
    cont2=0
    ranking={}
    for prov in lstFarmacia:
        if "Mutual" == prov["origen_financiamiento"] and provincia1 ==prov["provincia_nombre"]:
            cont1+=1
            ranking[provincia1] = cont1
        elif "Mutual" ==prov["origen_financiamiento"] and provincia2 == ["provincia_nombre"]:
            cont2+=1
            ranking [provincia2] = cont2
    entry_nombmutual.set((max(ranking,key=ranking.get )))
    entry_cantmutual.set(max(ranking.values()))



def buscar_postal():
    menor=int(entry_cpdesde.get())
    mayor=int(cphasta.get())
    contad=0
    for datos in lstFarmacia:
        if menor <= int(datos["cp"]) and mayor >= int(datos["cp"]):
            contad+=1
    entry_cantidad.set(contad)

def buscarid():
    buscid=Entry_id.get()
    for datos in lstFarmacia:
        if datos ["establecimiento_id"] == buscid:
            entry_nombre.set(datos["establecimiento_nombre"])
            entry_loca.set(datos["localidad_nombre"])
            entry_prov.set(datos["provincia_nombre"])
            entry_depar.set(datos["departamento_nombre"])
            entry_financ.set(datos["origen_financiamiento"])
            entry_domicilio.set(datos["domicilio"])

def cal_promedio():
    promingprov.set(promingprov.get().upper())
    nombre_prov = promingprov.get()
    financ = finanprom.get()
    tot = 1
    contar_finan = 1
    lsttotal = []
    lstFinancimiento = []
    lst2 = []
    for datosprovincia in lstFarmacia:
        if promingprov.get() == datosprovincia['provincia_nombre']:
            provincia = datosprovincia['provincia_nombre']
            lstFinancimiento.append(datosprovincia)
            lsttotal.append(provincia)
            tot = lsttotal.count(nombre_prov)
    for finan_ori in lstFinancimiento:
        if finanprom.get() == finan_ori['origen_financiamiento']:
            finan = finan_ori['origen_financiamiento']
            lst2.append(finan)
            contar_finan = lst2.count(financ)
    Promedio = round((contar_finan * 100 / tot),2)
    entry_cantProm.set(str(Promedio)+ str(" %"))



def calcularprov():
    contador=0
    ingresarprovincia=ingreprov.get()
    for datos in lstFarmacia:
        if datos ["provincia_nombre"] == ingresarprovincia:
            contador+=1
    cantfarmacia.set(contador)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Farmacias
    Farmacias.vp_start_gui()




