#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  May 18, 2020 11:31:28 AM -03  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m77" -background #b7edfb -cursor pencil \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 984x832+469+66
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 0 1
    wm deiconify $top
    wm title $top "Buscador De Farmacias"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab45 \
        -activebackground #f9f9f9 -activeforeground black -background #b7edfb \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Ingrese una Provincia:} 
    vTcl:DefineAlias "$top.lab45" "Label1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab45
    ttk::combobox $top.tCo46 \
        -font TkTextFont -textvariable comboboxProvincias -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo46" "combo_box_provincias" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.tCo46
    button $top.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #b7edfb \
        -background #80d2ff -command calcular_cantidad_farmacias \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Calcular 
    vTcl:DefineAlias "$top.but48" "btn_calcular_cant_f" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but48
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black -background #b7edfb \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Cantidad de Farmacias:} 
    vTcl:DefineAlias "$top.lab49" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #0086ff \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground #ffffff -highlightbackground #00ffff \
        -highlightcolor black -relief groove -text 0 -textvariable cant_f 
    vTcl:DefineAlias "$top.lab50" "lbl_cant_f" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra52 \
        -borderwidth 2 -relief sunken -background #b7edfb -cursor arrow \
        -height 245 -highlightbackground #000000 -highlightcolor #000000 \
        -width 965 
    vTcl:DefineAlias "$top.fra52" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra52
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black -background #b7edfb \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Establecimiento ID :} 
    vTcl:DefineAlias "$site_3_0.lab53" "Label1_2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #80d2ff -command buscar_id_farmacia \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Buscar 
    vTcl:DefineAlias "$site_3_0.but54" "btn_buscar_id" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent55 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable entry_far_id -width 224 
    vTcl:DefineAlias "$site_3_0.ent55" "entry_id_far" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black -background #b7edfb \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text NOMBRE: 
    vTcl:DefineAlias "$site_3_0.lab56" "Label1_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab57 \
        -activebackground #f9f9f9 -activeforeground black -background #0086ff \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 9 -weight bold} \
        -foreground #ffffff -highlightbackground #00ffff \
        -highlightcolor black -relief groove -text ------------ \
        -textvariable nombre_id 
    vTcl:DefineAlias "$site_3_0.lab57" "lbl_nombre_id" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab58 \
        -activebackground #f9f9f9 -activeforeground black -background #b7edfb \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text LOCALIDAD: 
    vTcl:DefineAlias "$site_3_0.lab58" "Label1_4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black -background #0086ff \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground #ffffff -highlightbackground #00ffff \
        -highlightcolor black -relief groove -text ------------- \
        -textvariable localidad_id 
    vTcl:DefineAlias "$site_3_0.lab59" "lbl_localidad_id" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black -background #b7edfb \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text PROVINCIA: 
    vTcl:DefineAlias "$site_3_0.lab60" "Label1_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black -background #0086ff \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground #ffffff -highlightbackground #00ffff \
        -highlightcolor black -relief groove -text ------------- \
        -textvariable provincia_id 
    vTcl:DefineAlias "$site_3_0.lab61" "lbl_provincia_id" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black -background #b7edfb \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text DEPARTAMENTO: 
    vTcl:DefineAlias "$site_3_0.lab62" "Label1_6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab63 \
        -activebackground #f9f9f9 -activeforeground black -background #0086ff \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground #ffffff -highlightbackground #00ffff \
        -highlightcolor black -relief groove -text ------------- \
        -textvariable depart_id 
    vTcl:DefineAlias "$site_3_0.lab63" "lbl_departamento_id" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab65 \
        -activebackground #f9f9f9 -activeforeground black -background #0086ff \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground #ffffff -highlightbackground #00ffff \
        -highlightcolor black -relief groove -text ------------ \
        -textvariable financiamiento_id 
    vTcl:DefineAlias "$site_3_0.lab65" "lbl_financiamiento_id" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab66 \
        -activebackground #f9f9f9 -activeforeground black -background #b7edfb \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text FINACIAMIENTO: 
    vTcl:DefineAlias "$site_3_0.lab66" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab67 \
        -activebackground #f9f9f9 -activeforeground black -background #b7edfb \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text DOMICILIO: 
    vTcl:DefineAlias "$site_3_0.lab67" "Label1_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab68 \
        -activebackground #f9f9f9 -activeforeground black -background #0086ff \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground #ffffff -highlightbackground #00ffff \
        -highlightcolor black -relief groove -text ------------ \
        -textvariable domicilio_id 
    vTcl:DefineAlias "$site_3_0.lab68" "lbl_domicilio_id" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab53 \
        -in $site_3_0 -x 30 -y 10 -width 241 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 520 -y 10 -width 116 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent55 \
        -in $site_3_0 -x 280 -y 10 -width 224 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 10 -y 70 -width 111 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 120 -y 70 -width 369 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 10 -y 110 -width 131 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 190 -y 110 -width 289 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 20 -y 150 -width 131 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 190 -y 150 -width 289 -height 32 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 10 -y 190 -width 171 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 190 -y 190 -width 289 -height 32 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 680 -y 70 -width 269 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 490 -y 70 -width 181 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 520 -y 120 -width 181 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 680 -y 120 -width 269 -relwidth 0 -height 132 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.fra52
    frame $top.fra70 \
        -borderwidth 2 -relief groove -background #b7edfb -height 115 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 965 
    vTcl:DefineAlias "$top.fra70" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra70
    label $site_3_0.lab71 \
        -activebackground #f9f9f9 -activeforeground black -background #b7edfb \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {COD. POSTAL DESDE:} 
    vTcl:DefineAlias "$site_3_0.lab71" "Label1_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab72 \
        -activebackground #f9f9f9 -activeforeground black -background #b7edfb \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {COD. POSTAL HASTA:} 
    vTcl:DefineAlias "$site_3_0.lab72" "Label1_4" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent74 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable codPost1 -width 124 
    vTcl:DefineAlias "$site_3_0.ent74" "entry_cod_post_des" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent75 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable codPost2 -width 124 
    vTcl:DefineAlias "$site_3_0.ent75" "entry_cod_post_has" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but76 \
        -activebackground $vTcl(analog_color_m) -activeforeground #b7edfb \
        -background #80d2ff -command calcular_cant_cod_postal \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Calcular 
    vTcl:DefineAlias "$site_3_0.but76" "btn_calcular_cod_pos" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab78 \
        -activebackground #f9f9f9 -activeforeground black -background #b7edfb \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Cantidad: 
    vTcl:DefineAlias "$site_3_0.lab78" "Label1_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab79 \
        -activebackground #f9f9f9 -activeforeground black -background #0086ff \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground #ffffff -highlightbackground #00ffff \
        -highlightcolor black -relief groove -text 0 \
        -textvariable cant_far_cod 
    vTcl:DefineAlias "$site_3_0.lab79" "lbl_cant_cod" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab71 \
        -in $site_3_0 -x 20 -y 10 -width 221 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab72 \
        -in $site_3_0 -x 20 -y 60 -width 221 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent74 \
        -in $site_3_0 -x 250 -y 10 -width 124 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent75 \
        -in $site_3_0 -x 250 -y 60 -width 124 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but76 \
        -in $site_3_0 -x 430 -y 20 -width 116 -height 43 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 570 -y 30 -width 111 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab79 \
        -in $site_3_0 -x 680 -y 30 -width 119 -height 32 -anchor nw \
        -bordermode ignore 
    set site_3_0 $top.m77
    menu $site_3_0 \
        -activebackground SystemHighlight \
        -activeforeground SystemHighlightText \
        -background $vTcl(pr,menubgcolor) -font TkDefaultFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    frame $top.fra80 \
        -borderwidth 2 -relief groove -background #b7edfb -height 125 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 965 
    vTcl:DefineAlias "$top.fra80" "Frame2_4" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra80
    button $site_3_0.but76 \
        -activebackground $vTcl(analog_color_m) -activeforeground #b7edfb \
        -background #80d2ff -command provincia_mas_f_origen_m \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text mostrar 
    vTcl:DefineAlias "$site_3_0.but76" "btn_calcular_m" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab78 \
        -activebackground #f9f9f9 -activeforeground black -background #b7edfb \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Cantidad: 
    vTcl:DefineAlias "$site_3_0.lab78" "Label1_4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab79 \
        -activebackground #f9f9f9 -activeforeground black -background #0086ff \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground #ffffff -highlightbackground #00ffff \
        -highlightcolor black -relief groove -text 0 -textvariable cant_far_m 
    vTcl:DefineAlias "$site_3_0.lab79" "lbl_cant_m" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab81 \
        -activebackground #f9f9f9 -activeforeground black -background #b7edfb \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Provincia con más farmacias cuyo origen de financiamiento sea "mutual":} 
    vTcl:DefineAlias "$site_3_0.lab81" "Label1_4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab85 \
        -activebackground #f9f9f9 -activeforeground black -background #b7edfb \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Nombre: 
    vTcl:DefineAlias "$site_3_0.lab85" "Label1_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab86 \
        -activebackground #f9f9f9 -activeforeground black -background #0086ff \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground #ffffff -highlightbackground #00ffff \
        -highlightcolor black -relief groove -text ----- \
        -textvariable nombre_prov 
    vTcl:DefineAlias "$site_3_0.lab86" "lbl_nombre_m" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but76 \
        -in $site_3_0 -x 140 -y 60 -width 116 -height 43 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 280 -y 80 -width 111 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab79 \
        -in $site_3_0 -x 390 -y 80 -width 119 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab81 \
        -in $site_3_0 -x 100 -y 10 -width 721 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab85 \
        -in $site_3_0 -x 280 -y 40 -width 111 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab86 \
        -in $site_3_0 -x 390 -y 40 -width 119 -height 32 -anchor nw \
        -bordermode ignore 
    frame $top.fra82 \
        -borderwidth 2 -relief groove -background #b7edfb -height 115 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 965 
    vTcl:DefineAlias "$top.fra82" "Frame2_5" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra82
    label $site_3_0.lab71 \
        -activebackground #f9f9f9 -activeforeground black -background #b7edfb \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {INGRESE UNA PROVINCIA:} 
    vTcl:DefineAlias "$site_3_0.lab71" "Label1_6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab72 \
        -activebackground #f9f9f9 -activeforeground black -background #b7edfb \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {UN FINANCIAMIENTO:} 
    vTcl:DefineAlias "$site_3_0.lab72" "Label1_7" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but76 \
        -activebackground $vTcl(analog_color_m) -activeforeground #b7edfb \
        -background #80d2ff -command prom_de_far_por_dep \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Promedio por departamento} 
    vTcl:DefineAlias "$site_3_0.but76" "btn_prom_dep" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab78 \
        -activebackground #f9f9f9 -activeforeground black -background #b7edfb \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Cantidad: 
    vTcl:DefineAlias "$site_3_0.lab78" "Label1_4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab79 \
        -activebackground #f9f9f9 -activeforeground black -background #0086ff \
        -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 11 -weight bold} \
        -foreground #ffffff -highlightbackground #00ffff \
        -highlightcolor black -relief groove -text 0.0 \
        -textvariable cant_prom 
    vTcl:DefineAlias "$site_3_0.lab79" "lbl_cant_p" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_3_0.tCo83 \
        -font TkTextFont -textvariable comboboxProvProm -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo83" "combobox_prov_p" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_3_0.tCo84 \
        -font TkTextFont -textvariable comboboxFinan -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo84" "combobox_finan_p" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab71 \
        -in $site_3_0 -x 50 -y 10 -width 311 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab72 \
        -in $site_3_0 -x 120 -y 60 -width 221 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but76 \
        -in $site_3_0 -x 490 -y 30 -width 296 -relwidth 0 -height 43 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 820 -y 20 -width 111 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab79 \
        -in $site_3_0 -x 820 -y 60 -width 119 -height 32 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo83 \
        -in $site_3_0 -x 350 -y 10 -width 127 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo84 \
        -in $site_3_0 -x 350 -y 60 -width 127 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab45 \
        -in $top -x 40 -y 30 -width 241 -relwidth 0 -height 26 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo46 \
        -in $top -x 300 -y 30 -width 187 -relwidth 0 -height 26 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 500 -y 20 -width 116 -relwidth 0 -height 43 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 620 -y 30 -width 241 -height 26 -anchor nw \
        -bordermode ignore 
    place $top.lab50 \
        -in $top -x 860 -y 30 -width 119 -relwidth 0 -height 32 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra52 \
        -in $top -x 10 -y 100 -width 965 -relwidth 0 -height 245 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra70 \
        -in $top -x 10 -y 380 -width 965 -relwidth 0 -height 115 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra80 \
        -in $top -x 10 -y 500 -width 965 -relwidth 0 -height 125 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra82 \
        -in $top -x 10 -y 640 -width 965 -height 115 -anchor nw \
        -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

