#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    May 16, 2020 12:44:12 PM -03  platform: Windows NT
#    May 16, 2020 12:47:01 PM -03  platform: Windows NT
#    May 16, 2020 12:55:09 PM -03  platform: Windows NT
#    May 17, 2020 04:00:07 PM -03  platform: Windows NT
#    May 17, 2020 04:09:02 PM -03  platform: Windows NT

import sys
import json
with open("farmaciass.json", encoding='utf-8') as archivodeFarmacias:
    listaDeFarmacias = json.load(archivodeFarmacias)

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global entry_far_id
    entry_far_id = tk.StringVar()
    global cant_f
    cant_f = tk.StringVar()
    global nombre_id
    nombre_id = tk.StringVar()
    nombre_id.set('------------')

    global localidad_id
    localidad_id = tk.StringVar()
    localidad_id.set('-------------')

    global provincia_id
    provincia_id = tk.StringVar()
    provincia_id.set('-------------')

    global depart_id
    depart_id = tk.StringVar()
    depart_id.set('-------------')

    global financiamiento_id
    financiamiento_id = tk.StringVar()
    financiamiento_id.set('------------')

    global domicilio_id
    domicilio_id = tk.StringVar()
    domicilio_id.set('------------')

    global cant_far_cod
    cant_far_cod = tk.StringVar()
    global cant_far_m
    cant_far_m = tk.StringVar()
    global nombre_prov
    nombre_prov = tk.StringVar()
    nombre_prov.set('-----')

    global cant_prom
    cant_prom = tk.StringVar()
    global comboboxProvincias
    comboboxProvincias = tk.StringVar()
    global codPost1
    codPost1 = tk.StringVar()
    global codPost2
    codPost2 = tk.StringVar()
    global comboboxProvProm
    comboboxProvProm = tk.StringVar()
    global comboboxFinan
    comboboxFinan = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root

    w = gui
    top_level = top
    root = top
    mostrar_nombres_prov()
    w.combo_box_provincias.configure(values=mostrar_nombres_prov(),state="readonly")
    mostrar_financiamiento()
    w.combobox_prov_p.configure(values=mostrar_nombres_prov(),state="readonly")
    w.combobox_finan_p.configure(values=mostrar_financiamiento(),state="readonly")



def buscar_id_farmacia():
    nombre_far="---"
    localidad_far="---"
    provincia_far="---"
    departamento_far="---"
    financiamiento_far="---"
    domicilio_far="---"
    for id_far in listaDeFarmacias:
        id_farmacia=id_far["establecimiento_id"]
        if  w.entry_id_far.get()==id_farmacia:
            print("ok")
            nombre_far=id_far["establecimiento_nombre"]
            localidad_far=id_far[ "localidad_nombre"]
            provincia_far=id_far["provincia_nombre"]
            departamento_far=id_far["departamento_nombre"]
            financiamiento_far=id_far["origen_financiamiento"]
            domicilio_far=id_far["domicilio"]
    nombre_id.set(nombre_far)
    localidad_id.set(localidad_far)
    provincia_id.set(provincia_far)
    depart_id.set(departamento_far)
    financiamiento_id.set(financiamiento_far)
    domicilio_id.set(domicilio_far)

    sys.stdout.flush()
#funciones para combox-------------------
def mostrar_nombres_prov():
    global listaNombresProv
    listaNombresProv = list()
    print(listaNombresProv)
    for nombre_pro in listaDeFarmacias:
        if nombre_pro["provincia_nombre"] in listaNombresProv:
            print("")
        else:
            listaNombresProv.append(nombre_pro["provincia_nombre"])
            print(listaNombresProv)
    return listaNombresProv
def mostrar_financiamiento():
    global listaFinan
    listaFinan=list()
    for finan in listaDeFarmacias:
        if finan["origen_financiamiento"] not in listaFinan:
            listaFinan.append(finan["origen_financiamiento"])
    return listaFinan
#-------------retorna la cantidad de departamentos por provincia-------------------------------------------------------------------
def cant_depart_por_provincia(provincia):
    lista_departamento=list()
    for un_departamento in listaDeFarmacias:
        if un_departamento["provincia_nombre"]==provincia:
            if un_departamento["departamento_nombre"]not in lista_departamento:
                lista_departamento.append(un_departamento["departamento_nombre"])
    return lista_departamento
def calcular_cant_cod_postal():
    contador=0
    for una_far in listaDeFarmacias:
        codP1=int(una_far['cp'])
        codP2 = int(una_far['cp'])
        if int(codP1)>=int(w.entry_cod_post_des.get()) and int(codP2)<=int(w.entry_cod_post_has.get()):
            contador+=1
    cant_far_cod.set(contador)


    sys.stdout.flush()

def calcular_cantidad_farmacias():
    print(len(listaDeFarmacias))
    print(w.combo_box_provincias.get())
    cont=0
    for cant_farma in listaDeFarmacias:
        if   w.combo_box_provincias.get()==str(cant_farma["provincia_nombre"]):
            cont+=1

    cant_f.set(cont)



    sys.stdout.flush()
def contadores_nombres_prov():
    lista_cont=list()
    listaNombres=mostrar_nombres_prov()
    for un_nombre in listaNombres:
        lista_cont.append({'nombre':un_nombre,'contador':0})
    return lista_cont
def provincia_mas_f_origen_m():
    lista_de_provincias=contadores_nombres_prov()
    mayor={'nombre': " ",'contador':0}
    for una_farmacia in listaDeFarmacias:
        if una_farmacia["origen_financiamiento"]=="Mutual":
            for una_provincia in lista_de_provincias:
                if una_provincia["nombre"]==una_farmacia["provincia_nombre"]:
                    una_provincia['contador']+=1
    for una_provincia in lista_de_provincias:
        if una_provincia['contador']>mayor['contador']:
            mayor=una_provincia
    nombre_prov.set(mayor['nombre'])
    cant_far_m.set(mayor['contador'])




    sys.stdout.flush()

def prom_de_far_por_dep():
    cant_dep=len(cant_depart_por_provincia( w.combobox_prov_p.get()))
    cont=0
    for una_farmacia in listaDeFarmacias:
        if una_farmacia["provincia_nombre"]==w.combobox_prov_p.get() and una_farmacia["origen_financiamiento"]==w.combobox_finan_p.get():
            cont+=1
    promedio=cont/cant_dep
    cant_prom.set(promedio)


    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import farmaciaGUI
    farmaciaGUI.vp_start_gui()





