#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    May 09, 2020 05:18:23 PM -03  platform: Windows NT
#    May 10, 2020 02:20:41 PM -03  platform: Windows NT
#    May 10, 2020 02:46:11 PM -03  platform: Windows NT

import abm_futbol
import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global lstDatos
    lstDatos = tk.StringVar()
    global lstNombre_equipo
    lstNombre_equipo = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def cargar_equipos():
    global listaPosiciones, lstPosiciones, w
    abm_futbol.ventana_cargar_equipos(top_level,lstNombre_equipo,lstDatos,w.lblY_equipo1,w.lblY_equipo2,w.lblY_equipo3,w.lblY_equipo4,w.lblY_equipo5,w.lblX_equipo1,w.lblX_equipo2,w.lblX_equipo3,w.lblX_equipo4,w.lblX_equipo5)

def registrar_partido():
    abm_futbol.ventana_partido(top_level,lstDatos,lstNombre_equipo)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import futbol
    futbol.vp_start_gui()





