#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    May 17, 2020 02:52:35 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import futbol_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    futbol_support.set_Tk_var()
    top = Toplevel1 (root)
    futbol_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    futbol_support.set_Tk_var()
    top = Toplevel1 (w)
    futbol_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("998x748+465+32")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.lblTitulo = tk.Label(top)
        self.lblTitulo.place(relx=0.0, rely=0.0, height=61, width=1008)
        self.lblTitulo.configure(activebackground="#f9f9f9")
        self.lblTitulo.configure(activeforeground="black")
        self.lblTitulo.configure(background="#e48321")
        self.lblTitulo.configure(disabledforeground="#a3a3a3")
        self.lblTitulo.configure(font="-family {Segoe UI} -size 18 -weight bold")
        self.lblTitulo.configure(foreground="#000000")
        self.lblTitulo.configure(highlightbackground="#d9d9d9")
        self.lblTitulo.configure(highlightcolor="black")
        self.lblTitulo.configure(text='''CAMPEONATO''')

        self.LabelframePosiciones = tk.LabelFrame(top)
        self.LabelframePosiciones.place(relx=0.02, rely=0.094, relheight=0.43
                , relwidth=0.969)
        self.LabelframePosiciones.configure(relief='groove')
        self.LabelframePosiciones.configure(foreground="black")
        self.LabelframePosiciones.configure(text='''Tabla de Posiciones''')
        self.LabelframePosiciones.configure(background="#d9d9d9")
        self.LabelframePosiciones.configure(highlightbackground="#d9d9d9")
        self.LabelframePosiciones.configure(highlightcolor="black")

        self.lblEquipo = tk.Label(self.LabelframePosiciones)
        self.lblEquipo.place(relx=0.085, rely=0.096, height=27, width=54
                , bordermode='ignore')
        self.lblEquipo.configure(activebackground="#f9f9f9")
        self.lblEquipo.configure(activeforeground="black")
        self.lblEquipo.configure(background="#d9d9d9")
        self.lblEquipo.configure(disabledforeground="#a3a3a3")
        self.lblEquipo.configure(foreground="#000000")
        self.lblEquipo.configure(highlightbackground="#d9d9d9")
        self.lblEquipo.configure(highlightcolor="black")
        self.lblEquipo.configure(text='''Equipo''')

        self.lblJugados = tk.Label(self.LabelframePosiciones)
        self.lblJugados.place(relx=0.254, rely=0.096, height=27, width=54
                , bordermode='ignore')
        self.lblJugados.configure(activebackground="#f9f9f9")
        self.lblJugados.configure(activeforeground="black")
        self.lblJugados.configure(background="#d9d9d9")
        self.lblJugados.configure(disabledforeground="#a3a3a3")
        self.lblJugados.configure(foreground="#000000")
        self.lblJugados.configure(highlightbackground="#d9d9d9")
        self.lblJugados.configure(highlightcolor="black")
        self.lblJugados.configure(text='''Jugados''')

        self.lblGanados = tk.Label(self.LabelframePosiciones)
        self.lblGanados.place(relx=0.339, rely=0.096, height=27, width=68
                , bordermode='ignore')
        self.lblGanados.configure(activebackground="#f9f9f9")
        self.lblGanados.configure(activeforeground="black")
        self.lblGanados.configure(background="#d9d9d9")
        self.lblGanados.configure(disabledforeground="#a3a3a3")
        self.lblGanados.configure(foreground="#000000")
        self.lblGanados.configure(highlightbackground="#d9d9d9")
        self.lblGanados.configure(highlightcolor="black")
        self.lblGanados.configure(text='''Ganados''')

        self.lblEmpatados = tk.Label(self.LabelframePosiciones)
        self.lblEmpatados.place(relx=0.434, rely=0.096, height=27, width=86
                , bordermode='ignore')
        self.lblEmpatados.configure(activebackground="#f9f9f9")
        self.lblEmpatados.configure(activeforeground="black")
        self.lblEmpatados.configure(background="#d9d9d9")
        self.lblEmpatados.configure(disabledforeground="#a3a3a3")
        self.lblEmpatados.configure(foreground="#000000")
        self.lblEmpatados.configure(highlightbackground="#d9d9d9")
        self.lblEmpatados.configure(highlightcolor="black")
        self.lblEmpatados.configure(text='''Empatados''')

        self.lblPerdidos = tk.Label(self.LabelframePosiciones)
        self.lblPerdidos.place(relx=0.55, rely=0.096, height=27, width=64
                , bordermode='ignore')
        self.lblPerdidos.configure(activebackground="#f9f9f9")
        self.lblPerdidos.configure(activeforeground="black")
        self.lblPerdidos.configure(background="#d9d9d9")
        self.lblPerdidos.configure(disabledforeground="#a3a3a3")
        self.lblPerdidos.configure(foreground="#000000")
        self.lblPerdidos.configure(highlightbackground="#d9d9d9")
        self.lblPerdidos.configure(highlightcolor="black")
        self.lblPerdidos.configure(text='''Perdidos''')

        self.lblFavor = tk.Label(self.LabelframePosiciones)
        self.lblFavor.place(relx=0.635, rely=0.096, height=27, width=95
                , bordermode='ignore')
        self.lblFavor.configure(activebackground="#f9f9f9")
        self.lblFavor.configure(activeforeground="black")
        self.lblFavor.configure(background="#d9d9d9")
        self.lblFavor.configure(disabledforeground="#a3a3a3")
        self.lblFavor.configure(foreground="#000000")
        self.lblFavor.configure(highlightbackground="#d9d9d9")
        self.lblFavor.configure(highlightcolor="black")
        self.lblFavor.configure(text='''Goles a Favor''')

        self.lblContra = tk.Label(self.LabelframePosiciones)
        self.lblContra.place(relx=0.751, rely=0.096, height=27, width=75
                , bordermode='ignore')
        self.lblContra.configure(activebackground="#f9f9f9")
        self.lblContra.configure(activeforeground="black")
        self.lblContra.configure(background="#d9d9d9")
        self.lblContra.configure(disabledforeground="#a3a3a3")
        self.lblContra.configure(foreground="#000000")
        self.lblContra.configure(highlightbackground="#d9d9d9")
        self.lblContra.configure(highlightcolor="black")
        self.lblContra.configure(text='''En Contra''')

        self.lblPuntos = tk.Label(self.LabelframePosiciones)
        self.lblPuntos.place(relx=0.176, rely=0.093, height=27, width=54
                , bordermode='ignore')
        self.lblPuntos.configure(activebackground="#f9f9f9")
        self.lblPuntos.configure(activeforeground="black")
        self.lblPuntos.configure(background="#d9d9d9")
        self.lblPuntos.configure(disabledforeground="#a3a3a3")
        self.lblPuntos.configure(foreground="#000000")
        self.lblPuntos.configure(highlightbackground="#d9d9d9")
        self.lblPuntos.configure(highlightcolor="black")
        self.lblPuntos.configure(text='''Puntos''')

        self.listboxEquipo = tk.Listbox(self.LabelframePosiciones)
        self.listboxEquipo.place(relx=0.074, rely=0.193, relheight=0.795
                , relwidth=0.085, bordermode='ignore')
        self.listboxEquipo.configure(background="#d9d9d9")
        self.listboxEquipo.configure(borderwidth="0")
        self.listboxEquipo.configure(disabledforeground="#a3a3a3")
        self.listboxEquipo.configure(font="TkFixedFont")
        self.listboxEquipo.configure(foreground="#000000")
        self.listboxEquipo.configure(highlightbackground="#d9d9d9")
        self.listboxEquipo.configure(highlightcolor="black")
        self.listboxEquipo.configure(selectbackground="#c4c4c4")
        self.listboxEquipo.configure(selectforeground="black")
        self.listboxEquipo.configure(listvariable=futbol_support.lstNombre_equipo)

        self.listboxDatos_equipos = tk.Listbox(self.LabelframePosiciones)
        self.listboxDatos_equipos.place(relx=0.19, rely=0.193, relheight=0.602
                , relwidth=0.745, bordermode='ignore')
        self.listboxDatos_equipos.configure(background="#d9d9d9")
        self.listboxDatos_equipos.configure(borderwidth="0")
        self.listboxDatos_equipos.configure(disabledforeground="#a3a3a3")
        self.listboxDatos_equipos.configure(font="TkFixedFont")
        self.listboxDatos_equipos.configure(foreground="#000000")
        self.listboxDatos_equipos.configure(highlightbackground="#d9d9d9")
        self.listboxDatos_equipos.configure(highlightcolor="black")
        self.listboxDatos_equipos.configure(selectbackground="#c4c4c4")
        self.listboxDatos_equipos.configure(selectforeground="black")
        self.listboxDatos_equipos.configure(listvariable=futbol_support.lstDatos)

        self.LabelframeGoles = tk.LabelFrame(top)
        self.LabelframeGoles.place(relx=0.0, rely=0.535, relheight=0.368
                , relwidth=1.001)
        self.LabelframeGoles.configure(relief='groove')
        self.LabelframeGoles.configure(foreground="black")
        self.LabelframeGoles.configure(text='''Tabla de Goles''')
        self.LabelframeGoles.configure(background="#d9d9d9")
        self.LabelframeGoles.configure(highlightbackground="#d9d9d9")
        self.LabelframeGoles.configure(highlightcolor="black")

        self.lblY_equipo1 = tk.Label(self.LabelframeGoles)
        self.lblY_equipo1.place(relx=0.02, rely=0.255, height=26, width=62
                , bordermode='ignore')
        self.lblY_equipo1.configure(activebackground="#f9f9f9")
        self.lblY_equipo1.configure(activeforeground="black")
        self.lblY_equipo1.configure(background="#d9d9d9")
        self.lblY_equipo1.configure(disabledforeground="#a3a3a3")
        self.lblY_equipo1.configure(foreground="#000000")
        self.lblY_equipo1.configure(highlightbackground="#d9d9d9")
        self.lblY_equipo1.configure(highlightcolor="black")
        self.lblY_equipo1.configure(text='''Equipo 1''')

        self.lblY_equipo2 = tk.Label(self.LabelframeGoles)
        self.lblY_equipo2.place(relx=0.02, rely=0.4, height=26, width=62
                , bordermode='ignore')
        self.lblY_equipo2.configure(activebackground="#f9f9f9")
        self.lblY_equipo2.configure(activeforeground="black")
        self.lblY_equipo2.configure(background="#d9d9d9")
        self.lblY_equipo2.configure(disabledforeground="#a3a3a3")
        self.lblY_equipo2.configure(foreground="#000000")
        self.lblY_equipo2.configure(highlightbackground="#d9d9d9")
        self.lblY_equipo2.configure(highlightcolor="black")
        self.lblY_equipo2.configure(text='''Equipo 2''')

        self.lblY_equipo3 = tk.Label(self.LabelframeGoles)
        self.lblY_equipo3.place(relx=0.02, rely=0.545, height=26, width=62
                , bordermode='ignore')
        self.lblY_equipo3.configure(activebackground="#f9f9f9")
        self.lblY_equipo3.configure(activeforeground="black")
        self.lblY_equipo3.configure(background="#d9d9d9")
        self.lblY_equipo3.configure(disabledforeground="#a3a3a3")
        self.lblY_equipo3.configure(foreground="#000000")
        self.lblY_equipo3.configure(highlightbackground="#d9d9d9")
        self.lblY_equipo3.configure(highlightcolor="black")
        self.lblY_equipo3.configure(text='''Equipo 3''')

        self.lblY_equipo4 = tk.Label(self.LabelframeGoles)
        self.lblY_equipo4.place(relx=0.02, rely=0.691, height=26, width=62
                , bordermode='ignore')
        self.lblY_equipo4.configure(activebackground="#f9f9f9")
        self.lblY_equipo4.configure(activeforeground="black")
        self.lblY_equipo4.configure(background="#d9d9d9")
        self.lblY_equipo4.configure(disabledforeground="#a3a3a3")
        self.lblY_equipo4.configure(foreground="#000000")
        self.lblY_equipo4.configure(highlightbackground="#d9d9d9")
        self.lblY_equipo4.configure(highlightcolor="black")
        self.lblY_equipo4.configure(text='''Equipo 4''')

        self.lblY_equipo5 = tk.Label(self.LabelframeGoles)
        self.lblY_equipo5.place(relx=0.02, rely=0.836, height=26, width=62
                , bordermode='ignore')
        self.lblY_equipo5.configure(activebackground="#f9f9f9")
        self.lblY_equipo5.configure(activeforeground="black")
        self.lblY_equipo5.configure(background="#d9d9d9")
        self.lblY_equipo5.configure(disabledforeground="#a3a3a3")
        self.lblY_equipo5.configure(foreground="#000000")
        self.lblY_equipo5.configure(highlightbackground="#d9d9d9")
        self.lblY_equipo5.configure(highlightcolor="black")
        self.lblY_equipo5.configure(text='''Equipo 5''')

        self.lblX_equipo1 = tk.Label(self.LabelframeGoles)
        self.lblX_equipo1.place(relx=0.154, rely=0.109, height=26, width=63
                , bordermode='ignore')
        self.lblX_equipo1.configure(activebackground="#f9f9f9")
        self.lblX_equipo1.configure(activeforeground="black")
        self.lblX_equipo1.configure(background="#d9d9d9")
        self.lblX_equipo1.configure(disabledforeground="#a3a3a3")
        self.lblX_equipo1.configure(foreground="#000000")
        self.lblX_equipo1.configure(highlightbackground="#d9d9d9")
        self.lblX_equipo1.configure(highlightcolor="black")
        self.lblX_equipo1.configure(text='''Equipo 1''')

        self.lblX_equipo2 = tk.Label(self.LabelframeGoles)
        self.lblX_equipo2.place(relx=0.328, rely=0.109, height=26, width=63
                , bordermode='ignore')
        self.lblX_equipo2.configure(activebackground="#f9f9f9")
        self.lblX_equipo2.configure(activeforeground="black")
        self.lblX_equipo2.configure(background="#d9d9d9")
        self.lblX_equipo2.configure(disabledforeground="#a3a3a3")
        self.lblX_equipo2.configure(foreground="#000000")
        self.lblX_equipo2.configure(highlightbackground="#d9d9d9")
        self.lblX_equipo2.configure(highlightcolor="black")
        self.lblX_equipo2.configure(text='''Equipo 2''')

        self.lblX_equipo3 = tk.Label(self.LabelframeGoles)
        self.lblX_equipo3.place(relx=0.512, rely=0.109, height=26, width=63
                , bordermode='ignore')
        self.lblX_equipo3.configure(activebackground="#f9f9f9")
        self.lblX_equipo3.configure(activeforeground="black")
        self.lblX_equipo3.configure(background="#d9d9d9")
        self.lblX_equipo3.configure(disabledforeground="#a3a3a3")
        self.lblX_equipo3.configure(foreground="#000000")
        self.lblX_equipo3.configure(highlightbackground="#d9d9d9")
        self.lblX_equipo3.configure(highlightcolor="black")
        self.lblX_equipo3.configure(text='''Equipo 3''')

        self.lblX_equipo4 = tk.Label(self.LabelframeGoles)
        self.lblX_equipo4.place(relx=0.686, rely=0.109, height=26, width=63
                , bordermode='ignore')
        self.lblX_equipo4.configure(activebackground="#f9f9f9")
        self.lblX_equipo4.configure(activeforeground="black")
        self.lblX_equipo4.configure(background="#d9d9d9")
        self.lblX_equipo4.configure(disabledforeground="#a3a3a3")
        self.lblX_equipo4.configure(foreground="#000000")
        self.lblX_equipo4.configure(highlightbackground="#d9d9d9")
        self.lblX_equipo4.configure(highlightcolor="black")
        self.lblX_equipo4.configure(text='''Equipo 4''')

        self.lblX_equipo5 = tk.Label(self.LabelframeGoles)
        self.lblX_equipo5.place(relx=0.87, rely=0.109, height=26, width=63
                , bordermode='ignore')
        self.lblX_equipo5.configure(activebackground="#f9f9f9")
        self.lblX_equipo5.configure(activeforeground="black")
        self.lblX_equipo5.configure(background="#d9d9d9")
        self.lblX_equipo5.configure(disabledforeground="#a3a3a3")
        self.lblX_equipo5.configure(foreground="#000000")
        self.lblX_equipo5.configure(highlightbackground="#d9d9d9")
        self.lblX_equipo5.configure(highlightcolor="black")
        self.lblX_equipo5.configure(text='''Equipo 5''')

        self.lbl1v1 = tk.Label(self.LabelframeGoles)
        self.lbl1v1.place(relx=0.164, rely=0.255, height=26, width=43
                , bordermode='ignore')
        self.lbl1v1.configure(activebackground="#f9f9f9")
        self.lbl1v1.configure(activeforeground="black")
        self.lbl1v1.configure(background="#d9d9d9")
        self.lbl1v1.configure(disabledforeground="#a3a3a3")
        self.lbl1v1.configure(foreground="#000000")
        self.lbl1v1.configure(highlightbackground="#d9d9d9")
        self.lbl1v1.configure(highlightcolor="black")
        self.lbl1v1.configure(text='''X''')

        self.lbl1v2 = tk.Label(self.LabelframeGoles)
        self.lbl1v2.place(relx=0.338, rely=0.255, height=26, width=43
                , bordermode='ignore')
        self.lbl1v2.configure(activebackground="#f9f9f9")
        self.lbl1v2.configure(activeforeground="black")
        self.lbl1v2.configure(background="#d9d9d9")
        self.lbl1v2.configure(disabledforeground="#a3a3a3")
        self.lbl1v2.configure(foreground="#000000")
        self.lbl1v2.configure(highlightbackground="#d9d9d9")
        self.lbl1v2.configure(highlightcolor="black")
        self.lbl1v2.configure(text='''-''')

        self.lbl1v3 = tk.Label(self.LabelframeGoles)
        self.lbl1v3.place(relx=0.522, rely=0.255, height=26, width=43
                , bordermode='ignore')
        self.lbl1v3.configure(activebackground="#f9f9f9")
        self.lbl1v3.configure(activeforeground="black")
        self.lbl1v3.configure(background="#d9d9d9")
        self.lbl1v3.configure(disabledforeground="#a3a3a3")
        self.lbl1v3.configure(foreground="#000000")
        self.lbl1v3.configure(highlightbackground="#d9d9d9")
        self.lbl1v3.configure(highlightcolor="black")
        self.lbl1v3.configure(text='''-''')

        self.lbl1v4 = tk.Label(self.LabelframeGoles)
        self.lbl1v4.place(relx=0.696, rely=0.255, height=26, width=43
                , bordermode='ignore')
        self.lbl1v4.configure(activebackground="#f9f9f9")
        self.lbl1v4.configure(activeforeground="black")
        self.lbl1v4.configure(background="#d9d9d9")
        self.lbl1v4.configure(disabledforeground="#a3a3a3")
        self.lbl1v4.configure(foreground="#000000")
        self.lbl1v4.configure(highlightbackground="#d9d9d9")
        self.lbl1v4.configure(highlightcolor="black")
        self.lbl1v4.configure(text='''-''')

        self.lbl1v5 = tk.Label(self.LabelframeGoles)
        self.lbl1v5.place(relx=0.88, rely=0.255, height=26, width=43
                , bordermode='ignore')
        self.lbl1v5.configure(activebackground="#f9f9f9")
        self.lbl1v5.configure(activeforeground="black")
        self.lbl1v5.configure(background="#d9d9d9")
        self.lbl1v5.configure(disabledforeground="#a3a3a3")
        self.lbl1v5.configure(foreground="#000000")
        self.lbl1v5.configure(highlightbackground="#d9d9d9")
        self.lbl1v5.configure(highlightcolor="black")
        self.lbl1v5.configure(text='''-''')

        self.lbl2v1 = tk.Label(self.LabelframeGoles)
        self.lbl2v1.place(relx=0.164, rely=0.4, height=26, width=43
                , bordermode='ignore')
        self.lbl2v1.configure(activebackground="#f9f9f9")
        self.lbl2v1.configure(activeforeground="black")
        self.lbl2v1.configure(background="#d9d9d9")
        self.lbl2v1.configure(disabledforeground="#a3a3a3")
        self.lbl2v1.configure(foreground="#000000")
        self.lbl2v1.configure(highlightbackground="#d9d9d9")
        self.lbl2v1.configure(highlightcolor="black")
        self.lbl2v1.configure(text='''-''')

        self.lbl2v2 = tk.Label(self.LabelframeGoles)
        self.lbl2v2.place(relx=0.338, rely=0.4, height=26, width=43
                , bordermode='ignore')
        self.lbl2v2.configure(activebackground="#f9f9f9")
        self.lbl2v2.configure(activeforeground="black")
        self.lbl2v2.configure(background="#d9d9d9")
        self.lbl2v2.configure(disabledforeground="#a3a3a3")
        self.lbl2v2.configure(foreground="#000000")
        self.lbl2v2.configure(highlightbackground="#d9d9d9")
        self.lbl2v2.configure(highlightcolor="black")
        self.lbl2v2.configure(text='''X''')

        self.lbl2v3 = tk.Label(self.LabelframeGoles)
        self.lbl2v3.place(relx=0.522, rely=0.4, height=26, width=43
                , bordermode='ignore')
        self.lbl2v3.configure(activebackground="#f9f9f9")
        self.lbl2v3.configure(activeforeground="black")
        self.lbl2v3.configure(background="#d9d9d9")
        self.lbl2v3.configure(disabledforeground="#a3a3a3")
        self.lbl2v3.configure(foreground="#000000")
        self.lbl2v3.configure(highlightbackground="#d9d9d9")
        self.lbl2v3.configure(highlightcolor="black")
        self.lbl2v3.configure(text='''-''')

        self.lbl2v4 = tk.Label(self.LabelframeGoles)
        self.lbl2v4.place(relx=0.696, rely=0.4, height=26, width=43
                , bordermode='ignore')
        self.lbl2v4.configure(activebackground="#f9f9f9")
        self.lbl2v4.configure(activeforeground="black")
        self.lbl2v4.configure(background="#d9d9d9")
        self.lbl2v4.configure(disabledforeground="#a3a3a3")
        self.lbl2v4.configure(foreground="#000000")
        self.lbl2v4.configure(highlightbackground="#d9d9d9")
        self.lbl2v4.configure(highlightcolor="black")
        self.lbl2v4.configure(text='''-''')

        self.lbl2v5 = tk.Label(self.LabelframeGoles)
        self.lbl2v5.place(relx=0.88, rely=0.4, height=26, width=43
                , bordermode='ignore')
        self.lbl2v5.configure(activebackground="#f9f9f9")
        self.lbl2v5.configure(activeforeground="black")
        self.lbl2v5.configure(background="#d9d9d9")
        self.lbl2v5.configure(disabledforeground="#a3a3a3")
        self.lbl2v5.configure(foreground="#000000")
        self.lbl2v5.configure(highlightbackground="#d9d9d9")
        self.lbl2v5.configure(highlightcolor="black")
        self.lbl2v5.configure(text='''-''')

        self.lbl3v1 = tk.Label(self.LabelframeGoles)
        self.lbl3v1.place(relx=0.164, rely=0.545, height=26, width=43
                , bordermode='ignore')
        self.lbl3v1.configure(activebackground="#f9f9f9")
        self.lbl3v1.configure(activeforeground="black")
        self.lbl3v1.configure(background="#d9d9d9")
        self.lbl3v1.configure(disabledforeground="#a3a3a3")
        self.lbl3v1.configure(foreground="#000000")
        self.lbl3v1.configure(highlightbackground="#d9d9d9")
        self.lbl3v1.configure(highlightcolor="black")
        self.lbl3v1.configure(text='''-''')

        self.lbl3v2 = tk.Label(self.LabelframeGoles)
        self.lbl3v2.place(relx=0.338, rely=0.545, height=26, width=43
                , bordermode='ignore')
        self.lbl3v2.configure(activebackground="#f9f9f9")
        self.lbl3v2.configure(activeforeground="black")
        self.lbl3v2.configure(background="#d9d9d9")
        self.lbl3v2.configure(disabledforeground="#a3a3a3")
        self.lbl3v2.configure(foreground="#000000")
        self.lbl3v2.configure(highlightbackground="#d9d9d9")
        self.lbl3v2.configure(highlightcolor="black")
        self.lbl3v2.configure(text='''-''')

        self.lbl3v3 = tk.Label(self.LabelframeGoles)
        self.lbl3v3.place(relx=0.522, rely=0.545, height=26, width=43
                , bordermode='ignore')
        self.lbl3v3.configure(activebackground="#f9f9f9")
        self.lbl3v3.configure(activeforeground="black")
        self.lbl3v3.configure(background="#d9d9d9")
        self.lbl3v3.configure(disabledforeground="#a3a3a3")
        self.lbl3v3.configure(foreground="#000000")
        self.lbl3v3.configure(highlightbackground="#d9d9d9")
        self.lbl3v3.configure(highlightcolor="black")
        self.lbl3v3.configure(text='''X''')

        self.lbl3v4 = tk.Label(self.LabelframeGoles)
        self.lbl3v4.place(relx=0.696, rely=0.545, height=26, width=43
                , bordermode='ignore')
        self.lbl3v4.configure(activebackground="#f9f9f9")
        self.lbl3v4.configure(activeforeground="black")
        self.lbl3v4.configure(background="#d9d9d9")
        self.lbl3v4.configure(disabledforeground="#a3a3a3")
        self.lbl3v4.configure(foreground="#000000")
        self.lbl3v4.configure(highlightbackground="#d9d9d9")
        self.lbl3v4.configure(highlightcolor="black")
        self.lbl3v4.configure(text='''-''')

        self.lbl3v5 = tk.Label(self.LabelframeGoles)
        self.lbl3v5.place(relx=0.88, rely=0.545, height=26, width=43
                , bordermode='ignore')
        self.lbl3v5.configure(activebackground="#f9f9f9")
        self.lbl3v5.configure(activeforeground="black")
        self.lbl3v5.configure(background="#d9d9d9")
        self.lbl3v5.configure(disabledforeground="#a3a3a3")
        self.lbl3v5.configure(foreground="#000000")
        self.lbl3v5.configure(highlightbackground="#d9d9d9")
        self.lbl3v5.configure(highlightcolor="black")
        self.lbl3v5.configure(text='''-''')

        self.lbl4v1 = tk.Label(self.LabelframeGoles)
        self.lbl4v1.place(relx=0.164, rely=0.691, height=26, width=43
                , bordermode='ignore')
        self.lbl4v1.configure(activebackground="#f9f9f9")
        self.lbl4v1.configure(activeforeground="black")
        self.lbl4v1.configure(background="#d9d9d9")
        self.lbl4v1.configure(disabledforeground="#a3a3a3")
        self.lbl4v1.configure(foreground="#000000")
        self.lbl4v1.configure(highlightbackground="#d9d9d9")
        self.lbl4v1.configure(highlightcolor="black")
        self.lbl4v1.configure(text='''-''')

        self.lbl4v2 = tk.Label(self.LabelframeGoles)
        self.lbl4v2.place(relx=0.338, rely=0.691, height=26, width=43
                , bordermode='ignore')
        self.lbl4v2.configure(activebackground="#f9f9f9")
        self.lbl4v2.configure(activeforeground="black")
        self.lbl4v2.configure(background="#d9d9d9")
        self.lbl4v2.configure(disabledforeground="#a3a3a3")
        self.lbl4v2.configure(foreground="#000000")
        self.lbl4v2.configure(highlightbackground="#d9d9d9")
        self.lbl4v2.configure(highlightcolor="black")
        self.lbl4v2.configure(text='''-''')

        self.lbl4v3 = tk.Label(self.LabelframeGoles)
        self.lbl4v3.place(relx=0.522, rely=0.691, height=26, width=43
                , bordermode='ignore')
        self.lbl4v3.configure(activebackground="#f9f9f9")
        self.lbl4v3.configure(activeforeground="black")
        self.lbl4v3.configure(background="#d9d9d9")
        self.lbl4v3.configure(disabledforeground="#a3a3a3")
        self.lbl4v3.configure(foreground="#000000")
        self.lbl4v3.configure(highlightbackground="#d9d9d9")
        self.lbl4v3.configure(highlightcolor="black")
        self.lbl4v3.configure(text='''-''')

        self.lbl4v4 = tk.Label(self.LabelframeGoles)
        self.lbl4v4.place(relx=0.696, rely=0.691, height=26, width=43
                , bordermode='ignore')
        self.lbl4v4.configure(activebackground="#f9f9f9")
        self.lbl4v4.configure(activeforeground="black")
        self.lbl4v4.configure(background="#d9d9d9")
        self.lbl4v4.configure(disabledforeground="#a3a3a3")
        self.lbl4v4.configure(foreground="#000000")
        self.lbl4v4.configure(highlightbackground="#d9d9d9")
        self.lbl4v4.configure(highlightcolor="black")
        self.lbl4v4.configure(text='''X''')

        self.lbl4v5 = tk.Label(self.LabelframeGoles)
        self.lbl4v5.place(relx=0.88, rely=0.691, height=26, width=43
                , bordermode='ignore')
        self.lbl4v5.configure(activebackground="#f9f9f9")
        self.lbl4v5.configure(activeforeground="black")
        self.lbl4v5.configure(background="#d9d9d9")
        self.lbl4v5.configure(disabledforeground="#a3a3a3")
        self.lbl4v5.configure(foreground="#000000")
        self.lbl4v5.configure(highlightbackground="#d9d9d9")
        self.lbl4v5.configure(highlightcolor="black")
        self.lbl4v5.configure(text='''-''')

        self.lbl5v1 = tk.Label(self.LabelframeGoles)
        self.lbl5v1.place(relx=0.164, rely=0.836, height=26, width=43
                , bordermode='ignore')
        self.lbl5v1.configure(activebackground="#f9f9f9")
        self.lbl5v1.configure(activeforeground="black")
        self.lbl5v1.configure(background="#d9d9d9")
        self.lbl5v1.configure(disabledforeground="#a3a3a3")
        self.lbl5v1.configure(foreground="#000000")
        self.lbl5v1.configure(highlightbackground="#d9d9d9")
        self.lbl5v1.configure(highlightcolor="black")
        self.lbl5v1.configure(text='''-''')

        self.lbl5v2 = tk.Label(self.LabelframeGoles)
        self.lbl5v2.place(relx=0.338, rely=0.836, height=26, width=43
                , bordermode='ignore')
        self.lbl5v2.configure(activebackground="#f9f9f9")
        self.lbl5v2.configure(activeforeground="black")
        self.lbl5v2.configure(background="#d9d9d9")
        self.lbl5v2.configure(disabledforeground="#a3a3a3")
        self.lbl5v2.configure(foreground="#000000")
        self.lbl5v2.configure(highlightbackground="#d9d9d9")
        self.lbl5v2.configure(highlightcolor="black")
        self.lbl5v2.configure(text='''-''')

        self.lbl5v3 = tk.Label(self.LabelframeGoles)
        self.lbl5v3.place(relx=0.522, rely=0.836, height=26, width=43
                , bordermode='ignore')
        self.lbl5v3.configure(activebackground="#f9f9f9")
        self.lbl5v3.configure(activeforeground="black")
        self.lbl5v3.configure(background="#d9d9d9")
        self.lbl5v3.configure(disabledforeground="#a3a3a3")
        self.lbl5v3.configure(foreground="#000000")
        self.lbl5v3.configure(highlightbackground="#d9d9d9")
        self.lbl5v3.configure(highlightcolor="black")
        self.lbl5v3.configure(text='''-''')

        self.lbl5v4 = tk.Label(self.LabelframeGoles)
        self.lbl5v4.place(relx=0.696, rely=0.836, height=26, width=43
                , bordermode='ignore')
        self.lbl5v4.configure(activebackground="#f9f9f9")
        self.lbl5v4.configure(activeforeground="black")
        self.lbl5v4.configure(background="#d9d9d9")
        self.lbl5v4.configure(disabledforeground="#a3a3a3")
        self.lbl5v4.configure(foreground="#000000")
        self.lbl5v4.configure(highlightbackground="#d9d9d9")
        self.lbl5v4.configure(highlightcolor="black")
        self.lbl5v4.configure(text='''-''')

        self.lbl5v5 = tk.Label(self.LabelframeGoles)
        self.lbl5v5.place(relx=0.88, rely=0.836, height=26, width=43
                , bordermode='ignore')
        self.lbl5v5.configure(activebackground="#f9f9f9")
        self.lbl5v5.configure(activeforeground="black")
        self.lbl5v5.configure(background="#d9d9d9")
        self.lbl5v5.configure(disabledforeground="#a3a3a3")
        self.lbl5v5.configure(foreground="#000000")
        self.lbl5v5.configure(highlightbackground="#d9d9d9")
        self.lbl5v5.configure(highlightcolor="black")
        self.lbl5v5.configure(text='''X''')

        self.btnCargar_equipos = tk.Button(top)
        self.btnCargar_equipos.place(relx=0.184, rely=0.922, height=33
                , width=246)
        self.btnCargar_equipos.configure(activebackground="#ececec")
        self.btnCargar_equipos.configure(activeforeground="#000000")
        self.btnCargar_equipos.configure(background="#d9d9d9")
        self.btnCargar_equipos.configure(command=futbol_support.cargar_equipos)
        self.btnCargar_equipos.configure(disabledforeground="#a3a3a3")
        self.btnCargar_equipos.configure(foreground="#000000")
        self.btnCargar_equipos.configure(highlightbackground="#d9d9d9")
        self.btnCargar_equipos.configure(highlightcolor="black")
        self.btnCargar_equipos.configure(pady="0")
        self.btnCargar_equipos.configure(text='''Cargar Equipos''')

        self.btnRegistrar_partido = tk.Button(top)
        self.btnRegistrar_partido.place(relx=0.512, rely=0.922, height=33
                , width=246)
        self.btnRegistrar_partido.configure(activebackground="#ececec")
        self.btnRegistrar_partido.configure(activeforeground="#000000")
        self.btnRegistrar_partido.configure(background="#d9d9d9")
        self.btnRegistrar_partido.configure(command=futbol_support.registrar_partido)
        self.btnRegistrar_partido.configure(disabledforeground="#a3a3a3")
        self.btnRegistrar_partido.configure(foreground="#000000")
        self.btnRegistrar_partido.configure(highlightbackground="#d9d9d9")
        self.btnRegistrar_partido.configure(highlightcolor="black")
        self.btnRegistrar_partido.configure(pady="0")
        self.btnRegistrar_partido.configure(state='disabled')
        self.btnRegistrar_partido.configure(text='''Registrar Partidos''')

if __name__ == '__main__':
    vp_start_gui()





