#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.2
#  in conjunction with Tcl version 8.6
#    May 16, 2020 05:51:06 PM -03  platform: Windows NT
#    May 16, 2020 07:29:09 PM -03  platform: Windows NT
#    May 16, 2020 08:02:03 PM -03  platform: Windows NT

import sys
import json

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global ingProvincia
    ingProvincia = tk.StringVar()
    global canProvincias
    canProvincias = tk.StringVar()
    global estaID
    estaID = tk.StringVar()
    global financiamiento
    financiamiento = tk.StringVar()
    global buscPro
    buscPro = tk.StringVar()
    global cont
    cont = tk.StringVar()
    global busID
    busID = tk.StringVar()
    global nom
    nom = tk.StringVar()
    global loc
    loc = tk.StringVar()
    global pro
    pro = tk.StringVar()
    global dep
    dep = tk.StringVar()
    global domi
    domi = tk.StringVar()
    global codigoDesde
    codigoDesde = tk.StringVar()
    global codigoHasta
    codigoHasta = tk.StringVar()
    global cantCodigo
    cantCodigo = tk.StringVar()
    global nomMutual
    nomMutual = tk.StringVar()
    global cantMututal
    cantMututal = tk.StringVar()
    global proPromedio
    proPromedio = tk.StringVar()
    global unFina
    unFina = tk.StringVar()
    global cantDpto
    cantDpto = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def botonCodigo():
    print('GUI_support.botonCodigo')
    sys.stdout.flush()
    menor=int(codigoDesde.get())
    mayor=int(codigoHasta.get())
    cont=0
    for datos in lstFarmacia:
        if menor <= int(datos["cp"]) and mayor >= int(datos["cp"]):
            cont+=1
            print(cont)
    cantCodigo.set(cont)

def busProvincia():
    print('GUI_support.busPro')
    sys.stdout.flush()
    contador=0
    INGPRO=ingProvincia.get()
    for datos in lstFarmacia:
        if datos["provincia_nombre"] == INGPRO:
            contador+=1
    canProvincias.set(contador)

def buscID():
    print('GUI_support.buscID')
    sys.stdout.flush()
    ID=estaID.get()
    for datos in lstFarmacia:
        if datos["establecimiento_id"] == ID:
            nom.set(datos["establecimiento_nombre"])
            loc.set(datos["localidad_nombre"])
            pro.set(datos["provincia_nombre"])
            dep.set(datos["departamento_nombre"])
            financiamiento.set(datos["origen_financiamiento"])
            domi.set(datos["domicilio"])
            

def finMutual():
    print('GUI_support.finMutual')
    sys.stdout.flush()
    cont=0
    cont1=0
    cont2=0
    for datos in lstFarmacia:
        if datos["provincia_id"] == "6" and datos["origen_financiamiento"] == "Mutual":
            cont+=1
        elif datos["provincia_id"] == "2" and datos["origen_financiamiento"] == "Mutual":
            cont1+=1
        elif datos["provincia_id"] == "42" and datos["origen_financiamiento"] == "Mutual":
            cont2+=1
        elif cont > cont1 and cont > cont2:
            cantMututal.set(cont)
            nomMutual.set("BUENOS AIRES")
        elif cont1 > cont and cont1 > cont2:
            cantMututal.set(cont1)
            nomMutual.set("CABA")
        elif cont2 > cont1 and cont2 > cont:
            cantMututal.set(cont2)
            nomMutual.set("FORMOSA")

def proDepto():
    print('GUI_support.proDepto')
    sys.stdout.flush()
    proPromedio.set(proPromedio.get().upper())
    provincia = proPromedio.get()
    financiamiento = unFina.get()
    total = 0
    contarFinanciamiento = 0
    lstTotal = []
    lstFinanciamiento = []
    lista = []
    for datos in lstFarmacia:
        if provincia == datos['provincia_nombre']:
            prov = datos['provincia_nombre']
            lstFinanciamiento.append(provincia)
            lstTotal.append(prov)
            total = lstTotal.count(provincia)
    for i in lstFarmacia:
        if financiamiento == i['origen_financiamiento']:
            finan = i['origen_financiamiento']
            lista.append(finan)
            contarFinanciamiento = lista.count(financiamiento)
    Promedio = round((contarFinanciamiento * 100 / total),2)
    cantDpto.set(str(Promedio)+ str(" %"))

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

with open('farmacias.json') as archivoFar:
    lstFarmacia = json.load(archivoFar)

if __name__ == '__main__':
    import GUI
    GUI.vp_start_gui()





