#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    May 15, 2020 07:34:05 PM -03  platform: Windows NT

import sys
from collections import Counter
import json
from tkinter import messagebox
from decimal import Decimal

with open('Farmacias.json', encoding = 'utf-8') as file:
    lstFarmacias = json.load(file)

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global comboFin
    comboFin = tk.StringVar()
    global entryProv01
    entryProv01 = tk.StringVar()
    global lbl_cantFarm
    lbl_cantFarm = tk.StringVar()
    lbl_cantFarm.set('')
    global entryID
    entryID = tk.StringVar()
    global lbl_IDnom
    lbl_IDnom = tk.StringVar()
    lbl_IDnom.set('')
    global lbl_IDLoc
    lbl_IDLoc = tk.StringVar()
    lbl_IDLoc.set('')
    global lbl_IDProv
    lbl_IDProv = tk.StringVar()
    lbl_IDProv.set('')
    global lbl_IDDpto
    lbl_IDDpto = tk.StringVar()
    lbl_IDDpto.set('')
    global lbl_IDFin
    lbl_IDFin = tk.StringVar()
    lbl_IDFin.set('')
    global lbl_IDDom
    lbl_IDDom = tk.StringVar()
    lbl_IDDom.set('')
    global lbl_est
    lbl_est = tk.StringVar()
    lbl_est.set('')
    global entryCPDesde
    entryCPDesde = tk.StringVar()
    global entryCPHasta
    entryCPHasta = tk.StringVar()
    global lbl_canPost
    lbl_canPost = tk.StringVar()
    lbl_canPost.set('')
    global entryProv02
    entryProv02 = tk.StringVar()
    global entryFinan02
    entryFinan02 = tk.StringVar()
    global lbl_Prom
    lbl_Prom = tk.StringVar()
    lbl_Prom.set('')
    global lbl_nomxProv
    lbl_nomxProv = tk.StringVar()
    lbl_nomxProv.set('')
    global lbl_xCant
    lbl_xCant = tk.StringVar()
    lbl_xCant.set('')

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def Calcular_Prom():
    entryProv02.set(entryProv02.get().upper())
    nombre_prov = entryProv02.get()
    tipo_financia = comboFin.get()
    total = 0
    contar_finan = 0
    lsttotal = []    
    lstFinan = []
    lista2 = []
    for provincia in lstFarmacias:
        if entryProv02.get() == provincia['provincia_nombre']:
            prov = provincia['provincia_nombre']
            lstFinan.append(provincia)
            lsttotal.append(prov)
            total = lsttotal.count(nombre_prov)
    for origen in lstFinan:
        if comboFin.get() == origen['origen_financiamiento']:
            finan = origen['origen_financiamiento']
            lista2.append(finan)
            contar_finan = lista2.count(tipo_financia)
    Prom = round((contar_finan * 100 / total),2)
    lbl_Prom.set(str(Prom)+ str(" %"))
                 
    
                    
             

def Calcular_porFinan():
    prov1 = "BUENOS AIRES"
    prov2 = "CABA"
    prov3 = "SANTA FE"
    contar1 = 0
    contar2 = 0
    contar3 = 0
    ranking = {}
    for provincia in lstFarmacias:
        if "Mutual" == provincia['origen_financiamiento'] and prov1 == provincia['provincia_nombre']:
            contar1 += 1
            ranking[prov1] = contar1
        elif "Mutual" == provincia['origen_financiamiento'] and prov2 == provincia['provincia_nombre']:  
            contar2 += 1
            ranking[prov2] = contar2
        elif "Mutual" == provincia['origen_financiamiento'] and prov3 == provincia['provincia_nombre']:  
            contar3 += 1
            ranking[prov3] = contar3
    lbl_nomxProv.set((max(ranking, key=ranking.get)))
    lbl_xCant.set(max(ranking.values()))
    print(ranking)
    
 



def buscarFarmaciaxID():
    nom = ""
    loc = ""
    prov = ""
    dpto = ""
    fin = ""
    dom = ""
    ID = ""
    for IDFar in lstFarmacias:
        IDFarmacia = IDFar['establecimiento_id']
        if entryID.get() == IDFar['establecimiento_id']:
            ID = IDFar['establecimiento_id']
            nom = IDFar['establecimiento_nombre']
            loc = IDFar['localidad_nombre']
            prov = IDFar['provincia_nombre'] 
            dpto = IDFar['departamento_nombre']
            fin = IDFar['origen_financiamiento']
            dom = IDFar['domicilio']
    lbl_IDnom.set(nom)
    lbl_IDLoc.set(loc)
    lbl_IDProv.set(prov)
    lbl_IDDpto.set(dpto)
    lbl_IDFin.set(fin)
    lbl_IDDom.set(dom)
        
        

    

def calcular_CP():
    listasCP = []
    CPtotal = []
    CPtotal2 = []
    x = entryCPDesde.get()
    y = entryCPHasta.get()
    for CP in lstFarmacias:
        codigo = CP['cp']
        if entryCPDesde.get() in codigo:
            listasCP.append(codigo)
        if entryCPHasta.get() in codigo:
            listasCP.append(codigo)
    conteo = len(listasCP)
    lbl_canPost.set(conteo)
    
    

        
    
def calcular_cantidadxprovincia():
    entryProv01.set(entryProv01.get().upper())
    Provincia = entryProv01.get()
    lista = []
    for Provincias in lstFarmacias:
        infoProvincia = Provincias['provincia_nombre']
        lista.append(infoProvincia)
        cant = lista.count(Provincia)
    lbl_cantFarm.set(cant)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import SistemaFarmacia
    SistemaFarmacia.vp_start_gui()




