#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    May 16, 2020 11:56:57 AM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import SistemaFarmacia_support
import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    SistemaFarmacia_support.set_Tk_var()
    top = Toplevel1 (root)
    SistemaFarmacia_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    SistemaFarmacia_support.set_Tk_var()
    top = Toplevel1 (w)
    SistemaFarmacia_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("868x643+292+0")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(0, 0)
        top.title("Quantum Pharma")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.frame01 = tk.Frame(top)
        self.frame01.place(relx=0.012, rely=0.156, relheight=0.134
                , relwidth=0.977)
        self.frame01.configure(relief='groove')
        self.frame01.configure(borderwidth="2")
        self.frame01.configure(relief="groove")
        self.frame01.configure(background="#d9d9d9")
        self.frame01.configure(highlightbackground="#d9d9d9")
        self.frame01.configure(highlightcolor="black")

        self.entryProv01 = ttk.Entry(self.frame01)
        self.entryProv01.place(relx=0.212, rely=0.465, relheight=0.244
                , relwidth=0.172)
        self.entryProv01.configure(textvariable=SistemaFarmacia_support.entryProv01)
        self.entryProv01.configure(takefocus="")
        self.entryProv01.configure(cursor="ibeam")

        self.btn_Calcular = ttk.Button(self.frame01)
        self.btn_Calcular.place(relx=0.413, rely=0.349, height=35, width=156)
        self.btn_Calcular.configure(command=SistemaFarmacia_support.calcular_cantidadxprovincia)
        self.btn_Calcular.configure(takefocus="")
        self.btn_Calcular.configure(text='''Calcular''')

        self.lbl01 = tk.Label(self.frame01)
        self.lbl01.place(relx=0.047, rely=0.465, height=21, width=134)
        self.lbl01.configure(activebackground="#f9f9f9")
        self.lbl01.configure(activeforeground="black")
        self.lbl01.configure(background="#d9d9d9")
        self.lbl01.configure(disabledforeground="#a3a3a3")
        self.lbl01.configure(font="-family {Arial} -size 10")
        self.lbl01.configure(foreground="#000000")
        self.lbl01.configure(highlightbackground="#d9d9d9")
        self.lbl01.configure(highlightcolor="black")
        self.lbl01.configure(text='''Ingrese una Provincia''')

        self.lbl02 = tk.Label(self.frame01)
        self.lbl02.place(relx=0.625, rely=0.465, height=21, width=124)
        self.lbl02.configure(activebackground="#f9f9f9")
        self.lbl02.configure(activeforeground="black")
        self.lbl02.configure(background="#d9d9d9")
        self.lbl02.configure(disabledforeground="#a3a3a3")
        self.lbl02.configure(font="-family {Arial} -size 10")
        self.lbl02.configure(foreground="#000000")
        self.lbl02.configure(highlightbackground="#d9d9d9")
        self.lbl02.configure(highlightcolor="black")
        self.lbl02.configure(text='''Cantidad Farmacias''')

        self.lbl_cantFarm = tk.Label(self.frame01)
        self.lbl_cantFarm.place(relx=0.778, rely=0.465, height=21, width=134)
        self.lbl_cantFarm.configure(activebackground="#f9f9f9")
        self.lbl_cantFarm.configure(activeforeground="black")
        self.lbl_cantFarm.configure(background="#d9d9d9")
        self.lbl_cantFarm.configure(disabledforeground="#a3a3a3")
        self.lbl_cantFarm.configure(foreground="#000000")
        self.lbl_cantFarm.configure(highlightbackground="#d9d9d9")
        self.lbl_cantFarm.configure(highlightcolor="black")
        self.lbl_cantFarm.configure(relief="ridge")
        self.lbl_cantFarm.configure(textvariable=SistemaFarmacia_support.lbl_cantFarm)

        self.frame02 = tk.Frame(top)
        self.frame02.place(relx=0.012, rely=0.295, relheight=0.305
                , relwidth=0.977)
        self.frame02.configure(relief='groove')
        self.frame02.configure(borderwidth="2")
        self.frame02.configure(relief="groove")
        self.frame02.configure(background="#d9d9d9")
        self.frame02.configure(highlightbackground="#d9d9d9")
        self.frame02.configure(highlightcolor="black")

        self.entryID = ttk.Entry(self.frame02)
        self.entryID.place(relx=0.177, rely=0.102, relheight=0.107
                , relwidth=0.208)
        self.entryID.configure(textvariable=SistemaFarmacia_support.entryID)
        self.entryID.configure(takefocus="")
        self.entryID.configure(cursor="ibeam")

        self.lbl03 = tk.Label(self.frame02)
        self.lbl03.place(relx=0.035, rely=0.102, height=21, width=113)
        self.lbl03.configure(activebackground="#f9f9f9")
        self.lbl03.configure(activeforeground="black")
        self.lbl03.configure(background="#d9d9d9")
        self.lbl03.configure(disabledforeground="#a3a3a3")
        self.lbl03.configure(font="-family {Arial} -size 10")
        self.lbl03.configure(foreground="#000000")
        self.lbl03.configure(highlightbackground="#d9d9d9")
        self.lbl03.configure(highlightcolor="black")
        self.lbl03.configure(text='''Establecimiento ID''')

        self.lbl04 = tk.Label(self.frame02)
        self.lbl04.place(relx=0.106, rely=0.357, height=21, width=53)
        self.lbl04.configure(activebackground="#f9f9f9")
        self.lbl04.configure(activeforeground="black")
        self.lbl04.configure(background="#d9d9d9")
        self.lbl04.configure(disabledforeground="#a3a3a3")
        self.lbl04.configure(font="-family {Arial} -size 10")
        self.lbl04.configure(foreground="#000000")
        self.lbl04.configure(highlightbackground="#d9d9d9")
        self.lbl04.configure(highlightcolor="black")
        self.lbl04.configure(text='''Nombre''')

        self.lbl05 = tk.Label(self.frame02)
        self.lbl05.place(relx=0.094, rely=0.51, height=21, width=63)
        self.lbl05.configure(activebackground="#f9f9f9")
        self.lbl05.configure(activeforeground="black")
        self.lbl05.configure(background="#d9d9d9")
        self.lbl05.configure(disabledforeground="#a3a3a3")
        self.lbl05.configure(font="-family {Arial} -size 10")
        self.lbl05.configure(foreground="#000000")
        self.lbl05.configure(highlightbackground="#d9d9d9")
        self.lbl05.configure(highlightcolor="black")
        self.lbl05.configure(text='''Localidad''')

        self.lbl06 = tk.Label(self.frame02)
        self.lbl06.place(relx=0.106, rely=0.663, height=21, width=53)
        self.lbl06.configure(activebackground="#f9f9f9")
        self.lbl06.configure(activeforeground="black")
        self.lbl06.configure(background="#d9d9d9")
        self.lbl06.configure(disabledforeground="#a3a3a3")
        self.lbl06.configure(font="-family {Arial} -size 10")
        self.lbl06.configure(foreground="#000000")
        self.lbl06.configure(highlightbackground="#d9d9d9")
        self.lbl06.configure(highlightcolor="black")
        self.lbl06.configure(text='''Provincia''')

        self.lbl07 = tk.Label(self.frame02)
        self.lbl07.place(relx=0.071, rely=0.816, height=21, width=83)
        self.lbl07.configure(activebackground="#f9f9f9")
        self.lbl07.configure(activeforeground="black")
        self.lbl07.configure(background="#d9d9d9")
        self.lbl07.configure(disabledforeground="#a3a3a3")
        self.lbl07.configure(font="-family {Arial} -size 10")
        self.lbl07.configure(foreground="#000000")
        self.lbl07.configure(highlightbackground="#d9d9d9")
        self.lbl07.configure(highlightcolor="black")
        self.lbl07.configure(text='''Departamento''')

        self.lbl08 = tk.Label(self.frame02)
        self.lbl08.place(relx=0.483, rely=0.357, height=21, width=93)
        self.lbl08.configure(activebackground="#f9f9f9")
        self.lbl08.configure(activeforeground="black")
        self.lbl08.configure(background="#d9d9d9")
        self.lbl08.configure(disabledforeground="#a3a3a3")
        self.lbl08.configure(font="-family {Arial} -size 10")
        self.lbl08.configure(foreground="#000000")
        self.lbl08.configure(highlightbackground="#d9d9d9")
        self.lbl08.configure(highlightcolor="black")
        self.lbl08.configure(text='''Financiamiento''')

        self.btn_Buscar = ttk.Button(self.frame02)
        self.btn_Buscar.place(relx=0.413, rely=0.051, height=35, width=156)
        self.btn_Buscar.configure(command=SistemaFarmacia_support.buscarFarmaciaxID)
        self.btn_Buscar.configure(takefocus="")
        self.btn_Buscar.configure(text='''Buscar''')

        self.lbl09 = tk.Label(self.frame02)
        self.lbl09.place(relx=0.531, rely=0.51, height=21, width=53)
        self.lbl09.configure(activebackground="#f9f9f9")
        self.lbl09.configure(activeforeground="black")
        self.lbl09.configure(background="#d9d9d9")
        self.lbl09.configure(disabledforeground="#a3a3a3")
        self.lbl09.configure(font="-family {Arial} -size 10")
        self.lbl09.configure(foreground="#000000")
        self.lbl09.configure(highlightbackground="#d9d9d9")
        self.lbl09.configure(highlightcolor="black")
        self.lbl09.configure(text='''Domicilio''')

        self.lbl_IDnom = tk.Label(self.frame02)
        self.lbl_IDnom.place(relx=0.177, rely=0.357, height=21, width=174)
        self.lbl_IDnom.configure(activebackground="#f9f9f9")
        self.lbl_IDnom.configure(activeforeground="black")
        self.lbl_IDnom.configure(background="#d9d9d9")
        self.lbl_IDnom.configure(disabledforeground="#a3a3a3")
        self.lbl_IDnom.configure(foreground="#000000")
        self.lbl_IDnom.configure(highlightbackground="#d9d9d9")
        self.lbl_IDnom.configure(highlightcolor="black")
        self.lbl_IDnom.configure(relief="ridge")
        self.lbl_IDnom.configure(textvariable=SistemaFarmacia_support.lbl_IDnom)

        self.lbl_IDLoc = tk.Label(self.frame02)
        self.lbl_IDLoc.place(relx=0.177, rely=0.51, height=21, width=174)
        self.lbl_IDLoc.configure(activebackground="#f9f9f9")
        self.lbl_IDLoc.configure(activeforeground="black")
        self.lbl_IDLoc.configure(background="#d9d9d9")
        self.lbl_IDLoc.configure(disabledforeground="#a3a3a3")
        self.lbl_IDLoc.configure(foreground="#000000")
        self.lbl_IDLoc.configure(highlightbackground="#d9d9d9")
        self.lbl_IDLoc.configure(highlightcolor="black")
        self.lbl_IDLoc.configure(relief="ridge")
        self.lbl_IDLoc.configure(textvariable=SistemaFarmacia_support.lbl_IDLoc)

        self.lbl_IDProv = tk.Label(self.frame02)
        self.lbl_IDProv.place(relx=0.177, rely=0.663, height=21, width=174)
        self.lbl_IDProv.configure(activebackground="#f9f9f9")
        self.lbl_IDProv.configure(activeforeground="black")
        self.lbl_IDProv.configure(background="#d9d9d9")
        self.lbl_IDProv.configure(disabledforeground="#a3a3a3")
        self.lbl_IDProv.configure(foreground="#000000")
        self.lbl_IDProv.configure(highlightbackground="#d9d9d9")
        self.lbl_IDProv.configure(highlightcolor="black")
        self.lbl_IDProv.configure(relief="ridge")
        self.lbl_IDProv.configure(textvariable=SistemaFarmacia_support.lbl_IDProv)

        self.lbl_IDDpto = tk.Label(self.frame02)
        self.lbl_IDDpto.place(relx=0.177, rely=0.816, height=21, width=174)
        self.lbl_IDDpto.configure(activebackground="#f9f9f9")
        self.lbl_IDDpto.configure(activeforeground="black")
        self.lbl_IDDpto.configure(background="#d9d9d9")
        self.lbl_IDDpto.configure(disabledforeground="#a3a3a3")
        self.lbl_IDDpto.configure(foreground="#000000")
        self.lbl_IDDpto.configure(highlightbackground="#d9d9d9")
        self.lbl_IDDpto.configure(highlightcolor="black")
        self.lbl_IDDpto.configure(relief="ridge")
        self.lbl_IDDpto.configure(textvariable=SistemaFarmacia_support.lbl_IDDpto)

        self.lbl_IDFin = tk.Label(self.frame02)
        self.lbl_IDFin.place(relx=0.601, rely=0.357, height=21, width=174)
        self.lbl_IDFin.configure(activebackground="#f9f9f9")
        self.lbl_IDFin.configure(activeforeground="black")
        self.lbl_IDFin.configure(background="#d9d9d9")
        self.lbl_IDFin.configure(disabledforeground="#a3a3a3")
        self.lbl_IDFin.configure(foreground="#000000")
        self.lbl_IDFin.configure(highlightbackground="#d9d9d9")
        self.lbl_IDFin.configure(highlightcolor="black")
        self.lbl_IDFin.configure(relief="ridge")
        self.lbl_IDFin.configure(textvariable=SistemaFarmacia_support.lbl_IDFin)

        self.lbl_IDDom = tk.Label(self.frame02)
        self.lbl_IDDom.place(relx=0.601, rely=0.51, height=81, width=284)
        self.lbl_IDDom.configure(activebackground="#f9f9f9")
        self.lbl_IDDom.configure(activeforeground="black")
        self.lbl_IDDom.configure(background="#d9d9d9")
        self.lbl_IDDom.configure(disabledforeground="#a3a3a3")
        self.lbl_IDDom.configure(foreground="#000000")
        self.lbl_IDDom.configure(highlightbackground="#d9d9d9")
        self.lbl_IDDom.configure(highlightcolor="black")
        self.lbl_IDDom.configure(relief="ridge")
        self.lbl_IDDom.configure(textvariable=SistemaFarmacia_support.lbl_IDDom)

        self.frame03 = tk.Frame(top)
        self.frame03.place(relx=0.012, rely=0.607, relheight=0.134
                , relwidth=0.977)
        self.frame03.configure(relief='groove')
        self.frame03.configure(borderwidth="2")
        self.frame03.configure(relief="groove")
        self.frame03.configure(background="#d9d9d9")
        self.frame03.configure(highlightbackground="#d9d9d9")
        self.frame03.configure(highlightcolor="black")

        self.lbl10 = tk.Label(self.frame03)
        self.lbl10.place(relx=0.024, rely=0.233, height=21, width=123)
        self.lbl10.configure(activebackground="#f9f9f9")
        self.lbl10.configure(activeforeground="black")
        self.lbl10.configure(background="#d9d9d9")
        self.lbl10.configure(disabledforeground="#a3a3a3")
        self.lbl10.configure(font="-family {Arial} -size 10")
        self.lbl10.configure(foreground="#000000")
        self.lbl10.configure(highlightbackground="#d9d9d9")
        self.lbl10.configure(highlightcolor="black")
        self.lbl10.configure(text='''Codigo Postal desde''')

        self.entryCPDesde = ttk.Entry(self.frame03)
        self.entryCPDesde.place(relx=0.177, rely=0.233, relheight=0.244
                , relwidth=0.209)
        self.entryCPDesde.configure(textvariable=SistemaFarmacia_support.entryCPDesde)
        self.entryCPDesde.configure(takefocus="")

        self.lbl11 = tk.Label(self.frame03)
        self.lbl11.place(relx=0.024, rely=0.581, height=21, width=123)
        self.lbl11.configure(activebackground="#f9f9f9")
        self.lbl11.configure(activeforeground="black")
        self.lbl11.configure(background="#d9d9d9")
        self.lbl11.configure(disabledforeground="#a3a3a3")
        self.lbl11.configure(font="-family {Arial} -size 10")
        self.lbl11.configure(foreground="#000000")
        self.lbl11.configure(highlightbackground="#d9d9d9")
        self.lbl11.configure(highlightcolor="black")
        self.lbl11.configure(text='''Codigo Postal hasta''')

        self.entryCPHasta = ttk.Entry(self.frame03)
        self.entryCPHasta.place(relx=0.177, rely=0.581, relheight=0.244
                , relwidth=0.209)
        self.entryCPHasta.configure(textvariable=SistemaFarmacia_support.entryCPHasta)
        self.entryCPHasta.configure(takefocus="")

        self.btn_Calcular_CP = ttk.Button(self.frame03)
        self.btn_Calcular_CP.place(relx=0.425, rely=0.349, height=35, width=156)
        self.btn_Calcular_CP.configure(command=SistemaFarmacia_support.calcular_CP)
        self.btn_Calcular_CP.configure(takefocus="")
        self.btn_Calcular_CP.configure(text='''Calcular''')

        self.lbl12 = tk.Label(self.frame03)
        self.lbl12.place(relx=0.66, rely=0.465, height=21, width=53)
        self.lbl12.configure(activebackground="#f9f9f9")
        self.lbl12.configure(activeforeground="black")
        self.lbl12.configure(background="#d9d9d9")
        self.lbl12.configure(disabledforeground="#a3a3a3")
        self.lbl12.configure(font="-family {Arial} -size 10")
        self.lbl12.configure(foreground="#000000")
        self.lbl12.configure(highlightbackground="#d9d9d9")
        self.lbl12.configure(highlightcolor="black")
        self.lbl12.configure(text='''Cantidad''')

        self.lbl_canPost = tk.Label(self.frame03)
        self.lbl_canPost.place(relx=0.731, rely=0.465, height=21, width=174)
        self.lbl_canPost.configure(activebackground="#f9f9f9")
        self.lbl_canPost.configure(activeforeground="black")
        self.lbl_canPost.configure(background="#d9d9d9")
        self.lbl_canPost.configure(disabledforeground="#a3a3a3")
        self.lbl_canPost.configure(foreground="#000000")
        self.lbl_canPost.configure(highlightbackground="#d9d9d9")
        self.lbl_canPost.configure(highlightcolor="black")
        self.lbl_canPost.configure(relief="ridge")
        self.lbl_canPost.configure(textvariable=SistemaFarmacia_support.lbl_canPost)

        self.frame05 = tk.Frame(top)
        self.frame05.place(relx=0.012, rely=0.871, relheight=0.118
                , relwidth=0.977)
        self.frame05.configure(relief='groove')
        self.frame05.configure(borderwidth="2")
        self.frame05.configure(relief="groove")
        self.frame05.configure(background="#d9d9d9")
        self.frame05.configure(highlightbackground="#d9d9d9")
        self.frame05.configure(highlightcolor="black")

        self.entryProv02 = ttk.Entry(self.frame05)
        self.entryProv02.place(relx=0.189, rely=0.132, relheight=0.276
                , relwidth=0.209)
        self.entryProv02.configure(textvariable=SistemaFarmacia_support.entryProv02)
        self.entryProv02.configure(takefocus="")

        self.btn_Calcular_Prom = ttk.Button(self.frame05)
        self.btn_Calcular_Prom.place(relx=0.425, rely=0.263, height=35
                , width=156)
        self.btn_Calcular_Prom.configure(command=SistemaFarmacia_support.Calcular_Prom)
        self.btn_Calcular_Prom.configure(takefocus="")
        self.btn_Calcular_Prom.configure(text='''Calcular Promedio''')

        self.lbl17 = tk.Label(self.frame05)
        self.lbl17.place(relx=0.66, rely=0.395, height=21, width=53)
        self.lbl17.configure(activebackground="#f9f9f9")
        self.lbl17.configure(activeforeground="black")
        self.lbl17.configure(background="#d9d9d9")
        self.lbl17.configure(disabledforeground="#a3a3a3")
        self.lbl17.configure(font="-family {Arial} -size 10")
        self.lbl17.configure(foreground="#000000")
        self.lbl17.configure(highlightbackground="#d9d9d9")
        self.lbl17.configure(highlightcolor="black")
        self.lbl17.configure(text='''Cantidad''')

        self.lbl_Prom = tk.Label(self.frame05)
        self.lbl_Prom.place(relx=0.731, rely=0.395, height=21, width=174)
        self.lbl_Prom.configure(activebackground="#f9f9f9")
        self.lbl_Prom.configure(activeforeground="black")
        self.lbl_Prom.configure(background="#d9d9d9")
        self.lbl_Prom.configure(disabledforeground="#a3a3a3")
        self.lbl_Prom.configure(foreground="#000000")
        self.lbl_Prom.configure(highlightbackground="#d9d9d9")
        self.lbl_Prom.configure(highlightcolor="black")
        self.lbl_Prom.configure(relief="ridge")
        self.lbl_Prom.configure(textvariable=SistemaFarmacia_support.lbl_Prom)

        self.lbl18 = tk.Label(self.frame05)
        self.lbl18.place(relx=0.035, rely=0.132, height=21, width=123)
        self.lbl18.configure(activebackground="#f9f9f9")
        self.lbl18.configure(activeforeground="black")
        self.lbl18.configure(background="#d9d9d9")
        self.lbl18.configure(disabledforeground="#a3a3a3")
        self.lbl18.configure(font="-family {Arial} -size 10")
        self.lbl18.configure(foreground="#000000")
        self.lbl18.configure(highlightbackground="#d9d9d9")
        self.lbl18.configure(highlightcolor="black")
        self.lbl18.configure(text='''Ingrese una Provincia''')

        self.lbl19 = tk.Label(self.frame05)
        self.lbl19.place(relx=0.024, rely=0.526, height=21, width=133)
        self.lbl19.configure(activebackground="#f9f9f9")
        self.lbl19.configure(activeforeground="black")
        self.lbl19.configure(background="#d9d9d9")
        self.lbl19.configure(disabledforeground="#a3a3a3")
        self.lbl19.configure(font="-family {Arial} -size 10")
        self.lbl19.configure(foreground="#000000")
        self.lbl19.configure(highlightbackground="#d9d9d9")
        self.lbl19.configure(highlightcolor="black")
        self.lbl19.configure(text='''Ingrese Financiamiento''')

        self.comboFin = ttk.Combobox(self.frame05)
        self.comboFin.place(relx=0.189, rely=0.526, relheight=0.276
                , relwidth=0.204)
        self.value_list = ['Mutual','Privado','Provincial',]
        self.comboFin.configure(values=self.value_list)
        self.comboFin.configure(textvariable=SistemaFarmacia_support.comboFin)
        self.comboFin.configure(takefocus="")

        self.frame04 = tk.Frame(top)
        self.frame04.place(relx=0.012, rely=0.747, relheight=0.118
                , relwidth=0.977)
        self.frame04.configure(relief='groove')
        self.frame04.configure(borderwidth="2")
        self.frame04.configure(relief="groove")
        self.frame04.configure(background="#d9d9d9")
        self.frame04.configure(highlightbackground="#d9d9d9")
        self.frame04.configure(highlightcolor="black")

        self.lbl13 = tk.Label(self.frame04)
        self.lbl13.place(relx=0.071, rely=0.132, height=21, width=263)
        self.lbl13.configure(activebackground="#f9f9f9")
        self.lbl13.configure(activeforeground="black")
        self.lbl13.configure(background="#d9d9d9")
        self.lbl13.configure(disabledforeground="#a3a3a3")
        self.lbl13.configure(font="-family {Arial} -size 10")
        self.lbl13.configure(foreground="#000000")
        self.lbl13.configure(highlightbackground="#d9d9d9")
        self.lbl13.configure(highlightcolor="black")
        self.lbl13.configure(text='''Provincia con Farmacias cuyo origen''')

        self.lbl14 = tk.Label(self.frame04)
        self.lbl14.place(relx=0.071, rely=0.395, height=21, width=263)
        self.lbl14.configure(activebackground="#f9f9f9")
        self.lbl14.configure(activeforeground="black")
        self.lbl14.configure(background="#d9d9d9")
        self.lbl14.configure(disabledforeground="#a3a3a3")
        self.lbl14.configure(font="-family {Arial} -size 10")
        self.lbl14.configure(foreground="#000000")
        self.lbl14.configure(highlightbackground="#d9d9d9")
        self.lbl14.configure(highlightcolor="black")
        self.lbl14.configure(text='''de Financiamiento sea "Mutual"''')

        self.btn_Calcular_porProv = ttk.Button(self.frame04)
        self.btn_Calcular_porProv.place(relx=0.425, rely=0.263, height=35
                , width=156)
        self.btn_Calcular_porProv.configure(command=SistemaFarmacia_support.Calcular_porFinan)
        self.btn_Calcular_porProv.configure(takefocus="")
        self.btn_Calcular_porProv.configure(text='''Calcular''')

        self.lbl16 = tk.Label(self.frame04)
        self.lbl16.place(relx=0.66, rely=0.526, height=21, width=53)
        self.lbl16.configure(activebackground="#f9f9f9")
        self.lbl16.configure(activeforeground="black")
        self.lbl16.configure(background="#d9d9d9")
        self.lbl16.configure(disabledforeground="#a3a3a3")
        self.lbl16.configure(font="-family {Arial} -size 10")
        self.lbl16.configure(foreground="#000000")
        self.lbl16.configure(highlightbackground="#d9d9d9")
        self.lbl16.configure(highlightcolor="black")
        self.lbl16.configure(text='''Cantidad''')

        self.lbl15 = tk.Label(self.frame04)
        self.lbl15.place(relx=0.66, rely=0.132, height=21, width=53)
        self.lbl15.configure(activebackground="#f9f9f9")
        self.lbl15.configure(activeforeground="black")
        self.lbl15.configure(background="#d9d9d9")
        self.lbl15.configure(disabledforeground="#a3a3a3")
        self.lbl15.configure(font="-family {Arial} -size 10")
        self.lbl15.configure(foreground="#000000")
        self.lbl15.configure(highlightbackground="#d9d9d9")
        self.lbl15.configure(highlightcolor="black")
        self.lbl15.configure(text='''Nombre''')

        self.lbl_nomxProv = tk.Label(self.frame04)
        self.lbl_nomxProv.place(relx=0.731, rely=0.132, height=21, width=174)
        self.lbl_nomxProv.configure(activebackground="#f9f9f9")
        self.lbl_nomxProv.configure(activeforeground="black")
        self.lbl_nomxProv.configure(background="#d9d9d9")
        self.lbl_nomxProv.configure(disabledforeground="#a3a3a3")
        self.lbl_nomxProv.configure(foreground="#000000")
        self.lbl_nomxProv.configure(highlightbackground="#d9d9d9")
        self.lbl_nomxProv.configure(highlightcolor="black")
        self.lbl_nomxProv.configure(relief="ridge")
        self.lbl_nomxProv.configure(textvariable=SistemaFarmacia_support.lbl_nomxProv)

        self.lbl_xCant = tk.Label(self.frame04)
        self.lbl_xCant.place(relx=0.731, rely=0.526, height=21, width=174)
        self.lbl_xCant.configure(activebackground="#f9f9f9")
        self.lbl_xCant.configure(activeforeground="black")
        self.lbl_xCant.configure(background="#d9d9d9")
        self.lbl_xCant.configure(disabledforeground="#a3a3a3")
        self.lbl_xCant.configure(foreground="#000000")
        self.lbl_xCant.configure(highlightbackground="#d9d9d9")
        self.lbl_xCant.configure(highlightcolor="black")
        self.lbl_xCant.configure(relief="ridge")
        self.lbl_xCant.configure(textvariable=SistemaFarmacia_support.lbl_xCant)

        self.Label_Top = tk.Label(top)
        self.Label_Top.place(relx=0.023, rely=0.0, height=91, width=804)
        self.Label_Top.configure(activebackground="#f9f9f9")
        self.Label_Top.configure(activeforeground="black")
        self.Label_Top.configure(background="#d9d9d9")
        self.Label_Top.configure(disabledforeground="#a3a3a3")
        self.Label_Top.configure(foreground="#000000")
        self.Label_Top.configure(highlightbackground="#d9d9d9")
        self.Label_Top.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"./TopLogo.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Label_Top.configure(image=_img0)

if __name__ == '__main__':
    vp_start_gui()





